"""
Ejemplos de respuestas para la documentación
"""
from .response_examples import (
    PRODUCT_LIST_EXAMPLE,
    PRODUCT_DETAIL_EXAMPLE,
    CART_ITEM_EXAMPLE,
    CART_DETAIL_EXAMPLE,
    SAVE_CART_REQUEST_EXAMPLE,
    SAVE_CART_RESPONSE_EXAMPLE,
    ERROR_STOCK_INSUFFICIENT,
    ERROR_PRODUCT_NOT_FOUND,
    ERROR_INVALID_QUANTITY,
    ERROR_VALIDATION,
)

__all__ = [
    'PRODUCT_LIST_EXAMPLE',
    'PRODUCT_DETAIL_EXAMPLE',
    'CART_ITEM_EXAMPLE',
    'CART_DETAIL_EXAMPLE',
    'SAVE_CART_REQUEST_EXAMPLE',
    'SAVE_CART_RESPONSE_EXAMPLE',
    'ERROR_STOCK_INSUFFICIENT',
    'ERROR_PRODUCT_NOT_FOUND',
    'ERROR_INVALID_QUANTITY',
    'ERROR_VALIDATION',
]